---
title: "Causal effects on Programming Score"
output: html_notebook
author: Christian Adriano
---

*Context:* Source code inspection is pervasive activity in software programming and might involve the inspection of dozens of lines of code. For this reason, experiments on these tasks require hundreds of participants. Although we can rely on crowdsourcing sites to reach out participants, there is no guarantee that particpants will have enough programming abilities to understand a source code that they have never seen.

*Problem:* A typical approach is to select participants by means of a programming test.  Since participants are recruited on the web, they take the test remotely. This makes it impossible to control if they were helped by other more skilled programmers. Hence, we have an inherent problem of how trustworthy is the test score of each participant. This is an important problem not only because unqualified participants might be selected, but also because test score is a predictor of the accuracy of the inspection tasks. Misclassification of participant´s test score has then the potential to insert noise in the interpretation of the experiment. 

*Goal:* Build causal inference models as competing explanation for test score of programmers. The causal models explain the test score as different functions of variables (covariates) collected for each participant. The covariates are: years of programming experience (yoe), profession (professional_developer, hobbyist, graduate_student, undergrad_student, other), gender (male, female, other), and the duration of the test (in seconds).

*Data:* The data was generated by a large experiment with real software bugs from different popular open source projects. Participants were recruited on Mechanical Turk and inspected the source code of a Java method that failed its unit test. 


```{r}
library(rethinking)
plot(cars)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.
